/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calendario.calendario;



/**
 *
 * @author Leo
 */
public final class Calendario extends javax.swing.JFrame {

    ManipuladorData data = new ManipuladorData();
    private final int meshj= data.meshoje;
    private final int anohj= data.anohoje;
    public Calendario() {
        initComponents();
        setResizable(false);
        inicializaCalendario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        header = new javax.swing.JPanel();
        avancaMes = new javax.swing.JLabel();
        ano = new javax.swing.JLabel();
        voltaMes = new javax.swing.JLabel();
        mes = new javax.swing.JLabel();
        header2 = new javax.swing.JPanel();
        qua = new javax.swing.JLabel();
        qui = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        sab = new javax.swing.JLabel();
        dom = new javax.swing.JLabel();
        diaslbl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmes = new javax.swing.JTable();
        seg = new javax.swing.JLabel();
        ter = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(255, 204, 204));
        header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        avancaMes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        avancaMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avancaMes.setText(">");
        avancaMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avancaMesMouseClicked(evt);
            }
        });

        ano.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ano.setText("ano");

        voltaMes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        voltaMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voltaMes.setText("<");
        voltaMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltaMesMouseClicked(evt);
            }
        });

        mes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mes.setText("mes");

        header2.setBackground(new java.awt.Color(255, 255, 255));

        qua.setBackground(new java.awt.Color(204, 204, 255));
        qua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qua.setText("QUA");
        qua.setOpaque(true);

        qui.setBackground(new java.awt.Color(204, 204, 255));
        qui.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qui.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qui.setText("QUI");
        qui.setOpaque(true);

        sex.setBackground(new java.awt.Color(204, 204, 255));
        sex.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sex.setText("SEX");
        sex.setOpaque(true);

        sab.setBackground(new java.awt.Color(204, 204, 255));
        sab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sab.setText("SAB");
        sab.setOpaque(true);

        dom.setBackground(new java.awt.Color(204, 204, 255));
        dom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dom.setForeground(new java.awt.Color(255, 0, 51));
        dom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dom.setText("DOM");
        dom.setOpaque(true);

        diaslbl.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setColumnHeaderView(null);

        tbmes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbmes.setColumnSelectionAllowed(true);
        tbmes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbmes.setFillsViewportHeight(true);
        tbmes.setFocusable(false);
        tbmes.setGridColor(new java.awt.Color(204, 0, 51));
        tbmes.setRowHeight(33);
        tbmes.setSelectionBackground(new java.awt.Color(255, 153, 153));
        tbmes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbmes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbmes.setShowGrid(false);
        tbmes.getTableHeader().setResizingAllowed(false);
        tbmes.getTableHeader().setReorderingAllowed(false);
        tbmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbmes);
        if (tbmes.getColumnModel().getColumnCount() > 0) {
            tbmes.getColumnModel().getColumn(0).setResizable(false);
            tbmes.getColumnModel().getColumn(1).setResizable(false);
            tbmes.getColumnModel().getColumn(2).setResizable(false);
            tbmes.getColumnModel().getColumn(3).setResizable(false);
            tbmes.getColumnModel().getColumn(4).setResizable(false);
            tbmes.getColumnModel().getColumn(5).setResizable(false);
            tbmes.getColumnModel().getColumn(6).setResizable(false);
        }
        tbmes.getAccessibleContext().setAccessibleName("");
        tbmes.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout diaslblLayout = new javax.swing.GroupLayout(diaslbl);
        diaslbl.setLayout(diaslblLayout);
        diaslblLayout.setHorizontalGroup(
            diaslblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        diaslblLayout.setVerticalGroup(
            diaslblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        seg.setBackground(new java.awt.Color(204, 204, 255));
        seg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        seg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seg.setText("SEG");
        seg.setOpaque(true);

        ter.setBackground(new java.awt.Color(204, 204, 255));
        ter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ter.setText("TER");
        ter.setOpaque(true);

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qui, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sab, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(diaslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qua)
                    .addComponent(qui)
                    .addComponent(sex)
                    .addComponent(sab)
                    .addComponent(dom)
                    .addComponent(seg)
                    .addComponent(ter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diaslbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltaMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avancaMes)
                .addGap(84, 84, 84)
                .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(header2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avancaMes)
                    .addComponent(voltaMes)
                    .addComponent(ano)
                    .addComponent(mes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmesMouseClicked
        //ano.setText((String) tbmes.getValueAt(tbmes.getSelectedRow(), tbmes.getSelectedColumn()));
    }//GEN-LAST:event_tbmesMouseClicked

    private void voltaMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltaMesMouseClicked
        data.manipulaCalendario(-1);
        inicializaCalendario();
    }//GEN-LAST:event_voltaMesMouseClicked

    private void avancaMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avancaMesMouseClicked
        data.manipulaCalendario(1);
        inicializaCalendario();
    }//GEN-LAST:event_avancaMesMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Calendario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ano;
    private javax.swing.JLabel avancaMes;
    private javax.swing.JPanel diaslbl;
    private javax.swing.JLabel dom;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mes;
    private javax.swing.JLabel qua;
    private javax.swing.JLabel qui;
    private javax.swing.JLabel sab;
    private javax.swing.JLabel seg;
    private javax.swing.JLabel sex;
    private javax.swing.JTable tbmes;
    private javax.swing.JLabel ter;
    private javax.swing.JLabel voltaMes;
    // End of variables declaration//GEN-END:variables
    public void inicializaCalendario(){
        limpaCelula();
        voltaMes.setVisible(travaVolta());
        preencheTabela();
        mes.setText(data.getMes());
        ano.setText(Integer.toString(data.anohoje));
    }
    public void preencheTabela(){
        int semana=data.semanaDoMes-1;
        int diasemana=data.diasemana-1;
        
        for(int cell=data.diahoje; cell<=data.diasmes; cell++){
            tbmes.setValueAt(cell, semana, diasemana);
            diasemana++;
            if(diasemana==7){
                diasemana=0;
                semana++;
            }
        }
    }
    public boolean travaVolta(){
            return !(anohj==data.anohoje && meshj==data.meshoje);
    }
    public void limpaCelula(){
        for(int i=0; i<6; i++){
            for(int j=0; j<7; j++){
                tbmes.setValueAt("", i, j);
            }
        }
    }
}

